export const GET_ALL_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const UPDATE_CATEGORY ='UPDATE_CATEGORY';
export const DELETE_CATEGORY ='DELETE_CATEGORY';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_ALL_PRODUCTS = 'ADD_PRODUCT';